In [1]:
import pandas as pd
import requests

In [2]:
P_record=pd.read_csv('patient_records.csv')
P_record.head(2)

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19
1,PT100001,Jessica,Smith,Female,53,O+,PA,Former,Medicaid,Anxiety Disorder,183.2,45.6,114,89,75,2025-01-16

In [3]:
res=requests.get('https://models.rcsb.org')

In [ ]:
pd.DataFrame(res.json()['results']).head()

In [ ]:
pd.DataFrame(res.json()['results']).head().[['structure', 'P_id', 'geometry']]

In [5]:
###  using loop 

df=pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
for i in range(1, 400):           ###  for example
    res=requests.get('https://models.rcsb.org')
    temp_df=pd.DataFrame(res.json()['results']).head().[['structure', 'P_id', 'geometry']]
    df=df.append(temp_df, ignore_index=True)

In [ ]:
df.shape

In [ ]:
df.to_csv('rscb.csv')        ###  we can upload

###  web scrapping -------> learn when html is done

In [ ]:
###  eg from ambition box

In [ ]:
from bs4 import BeautifulSoup

In [ ]:
headers={"user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/150.0.0.0 Safari/537.36"}
webpage=requests.get('https://www.imdb.com', headers=headers).text
webpage
###  will give the html code of the url website

In [ ]:
soup=BeautifulSoup(webpage, 'lxml')
print(soup.prettify())