In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [8]:
P_I=pd.read_csv('lab_results.csv')
P_I.head(2)

,lab_id,patient_id,test_name,result_value,reference_range_low,reference_range_high,flag,test_date,ordering_facility
0,LAB300000,PT101182,ALT (U/L),13.30,7.0,56.0,Normal,2024-09-20,Northside Clinic Lab
1,LAB300001,PT100847,Hemoglobin (g/dL),10.59,12.0,17.5,Low,2023-04-22,Northside Clinic Lab

In [31]:
P_I.shape

(4000, 9)

In [42]:
P_I['test_name'].unique()

<StringArray>
[                       'ALT (U/L)',                'Hemoglobin (g/dL)',
          'HDL Cholesterol (mg/dL)',               'Hemoglobin A1c (%)',
          'Fasting Glucose (mg/dL)',               'Creatinine (mg/dL)',
                      'TSH (mIU/L)',        'Total Cholesterol (mg/dL)',
          'LDL Cholesterol (mg/dL)', 'White Blood Cell Count (x10^9/L)']
Length: 10, dtype: str

In [43]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test=train_test_split(P_I['test_name'], P_I['flag'], test_size=0.3)

In [44]:
X_train

1087                   Hemoglobin (g/dL)
3516             Fasting Glucose (mg/dL)
3479    White Blood Cell Count (x10^9/L)
3421             LDL Cholesterol (mg/dL)
3147                   Hemoglobin (g/dL)
                      ...
3041                  Creatinine (mg/dL)
1855                           ALT (U/L)
1759                           ALT (U/L)
3814                         TSH (mIU/L)
1896             HDL Cholesterol (mg/dL)
Name: test_name, Length: 2800, dtype: str

In [45]:
X_train2=pd.DataFrame(X_train, columns=[X_train.name])
X_train2

                             test_name
1087                 Hemoglobin (g/dL)
3516           Fasting Glucose (mg/dL)
3479  White Blood Cell Count (x10^9/L)
3421           LDL Cholesterol (mg/dL)
3147                 Hemoglobin (g/dL)
...                                ...
3041                Creatinine (mg/dL)
1855                         ALT (U/L)
1759                         ALT (U/L)
3814                       TSH (mIU/L)
1896           HDL Cholesterol (mg/dL)

[2800 rows x 1 columns]

In [29]:
X_test

37      Normal
611     Normal
2227    Normal
1188      High
2351    Normal
         ...
2093       Low
2899    Normal
294     Normal
610     Normal
154     Normal
Name: flag, Length: 2000, dtype: str

In [46]:
X_test1=pd.DataFrame(X_test, columns=[X_test.name])
X_test1

                             test_name
3026                 Hemoglobin (g/dL)
358                        TSH (mIU/L)
1230           HDL Cholesterol (mg/dL)
1133                 Hemoglobin (g/dL)
2687                Creatinine (mg/dL)
...                                ...
1172           HDL Cholesterol (mg/dL)
3373                         ALT (U/L)
1220                Creatinine (mg/dL)
3247  White Blood Cell Count (x10^9/L)
1121                Creatinine (mg/dL)

[1200 rows x 1 columns]

In [36]:
from sklearn.preprocessing import OrdinalEncoder

In [47]:
oe=OrdinalEncoder(categories=[['ALT (U/L)', 'Hemoglobin (g/dL)', 'HDL Cholesterol (mg/dL)', 'Hemoglobin A1c (%)', 'Fasting Glucose (mg/dL)', 'Creatinine (mg/dL)',
                      'TSH (mIU/L)', 'Total Cholesterol (mg/dL)', 'LDL Cholesterol (mg/dL)', 'White Blood Cell Count (x10^9/L)']])

In [48]:
oe.fit(X_train2)

OrdinalEncoder(categories=[['ALT (U/L)', 'Hemoglobin (g/dL)',
                            'HDL Cholesterol (mg/dL)', 'Hemoglobin A1c (%)',
                            'Fasting Glucose (mg/dL)', 'Creatinine (mg/dL)',
                            'TSH (mIU/L)', 'Total Cholesterol (mg/dL)',
                            'LDL Cholesterol (mg/dL)',
                            'White Blood Cell Count (x10^9/L)']])

In [49]:
X_train1=oe.transform(X_train2)
X_test2=oe.transform(X_test1)

In [50]:
X_train1

array([[1.],
       [4.],
       [9.],
       ...,
       [0.],
       [6.],
       [2.]], shape=(2800, 1))

## label encoding on output column

In [51]:
from sklearn.preprocessing import LabelEncoder

In [52]:
le=LabelEncoder()

In [53]:
le.fit(Y_train)

LabelEncoder()

In [54]:
le.classes_

array(['High', 'Low', 'Normal'], dtype=object)

In [55]:
Y_train1=le.transform(Y_train)
Y_test2=le.transform(Y_test)

In [56]:
Y_train1

array([2, 2, 2, ..., 2, 2, 2], shape=(2800,))