In [23]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.impute import KNNImputer
from sklearn.compose import ColumnTransformer

from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression

In [3]:
Data = pd.read_csv('numeric_missing_target.csv')
Data.head()

    age  height_cm  weight_kg   income  hours_studied  temperature_c  passed
0  38.0      178.5       69.9  70767.0            NaN           27.5       1
1  50.0      170.8       74.9  59831.0            5.7           20.3       1
2  54.0      174.6       77.3      NaN            1.5            NaN       0
3  32.0        NaN       83.1  51300.0            6.1           25.2       1
4  61.0      175.0       85.2  67737.0            3.5           20.3       0

In [4]:
Data.isnull().sum()

age              4
height_cm        6
weight_kg        5
income           9
hours_studied    7
temperature_c    2
passed           0
dtype: int64

In [6]:
X = Data.drop(columns=['passed'])
X.head(2)

    age  height_cm  weight_kg   income  hours_studied  temperature_c
0  38.0      178.5       69.9  70767.0            NaN           27.5
1  50.0      170.8       74.9  59831.0            5.7           20.3

In [8]:
Y = Data['passed']

In [9]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3)
X_train.head(2)

     age  height_cm  weight_kg   income  hours_studied  temperature_c
13  49.0      178.6       79.3  48508.0            3.7           26.2
31  29.0      158.3       71.6  66836.0            7.5           21.0

In [33]:
# can do hit and trial with attribute values like neighbors, weights

kn = KNNImputer(n_neighbors = 5, weights = 'distance')

X_train_tr = kn.fit_transform(X_train)
X_test_tr = kn.fit_transform(X_test)

In [34]:
pd.DataFrame(X_train_tr, columns = X_train.columns)

,age,height_cm,weight_kg,income,hours_studied,temperature_c
0,49.000000,178.600000,79.300000,48508.000000,3.700000,26.200000
1,29.000000,158.300000,71.600000,66836.000000,7.500000,21.000000
2,46.000000,172.000000,74.590426,62942.000000,3.900000,26.400000
3,51.000000,152.300000,74.700000,55844.000000,5.000000,21.000000
4,34.000000,153.600000,57.700000,65979.000000,6.200000,27.900000
5,50.000000,157.400000,57.600000,67330.000000,5.400000,20.000000
6,53.069343,172.500000,70.900000,52732.000000,5.300000,25.044052
7,52.000000,172.260076,73.241563,66543.000000,7.400000,30.200000
8,63.000000,164.700000,59.600000,74015.000000,6.100000,13.900000
9,59.000000,181.400000,82.800000,83084.000000,3.100000,22.000000
10,26.000000,177.400000,53.600000,39530.000000,0.700000,16.900000
11,23.000000,179.200000,88.100000,45546.000000,2.700000,19.900000
12,22.000000,169.800000,71.900000,50678.000000,5.800000,19.200000
13,54.000000,174.600000,77.300000,60733.652212,1.500000,24.130488
14,25.000000,163.700000,67.800000,44447.000000,8.200000,13.100000
15,46.000000,168.100000,79.800000,59569.882476,4.600000,19.100000
16,50.000000,170.800000,74.900000,59831.000000,5.700000,20.300000
17,53.000000,174.700000,67.300000,59241.000000,5.700000,18.600000
18,61.000000,175.000000,85.200000,67737.000000,3.500000,20.300000
19,56.011031,185.900000,75.100000,38130.000000,5.200000,18.400000
20,41.000000,167.400000,66.200000,60729.000000,3.911946,13.700000
21,31.000000,144.000000,63.100000,51214.782028,4.900000,25.900000
22,21.000000,160.033101,58.200000,31110.000000,4.300000,10.900000
23,47.169285,162.300000,73.500000,62815.000000,5.700000,19.000000
24,32.000000,174.200000,70.800000,52177.000000,5.600000,22.700000
25,22.000000,158.400000,70.600000,35820.000000,4.900000,20.100000
26,43.000000,162.800000,71.883007,54067.146440,5.200000,27.300000
27,25.000000,162.500000,63.600000,37381.000000,4.700000,22.500000
28,59.000000,180.200000,90.400000,82917.000000,4.600000,18.300000
29,59.000000,168.700000,66.200000,64381.525386,2.900000,28.300000
30,34.000000,154.277024,63.400000,48405.000000,7.200000,25.500000
31,53.000000,175.500000,74.700000,70601.000000,5.200000,20.900000
32,59.000000,172.518370,60.800000,70766.000000,6.900000,26.300000
33,64.000000,192.400000,76.900000,63809.026783,6.100000,22.500000
34,32.000000,162.895706,83.100000,51300.000000,6.100000,25.200000
35,39.000000,169.000000,60.600000,61279.000000,4.900000,14.700000
36,64.000000,164.000000,59.200000,73260.000000,5.500000,23.300000
37,38.000000,165.500000,76.800000,42319.000000,5.100000,24.000000
38,52.000000,159.700000,62.500000,59183.000000,2.900000,24.000000
39,43.000000,177.600000,71.300000,61353.000000,6.400000,25.300000
40,30.000000,175.700000,53.200000,50635.000000,3.600000,17.300000
41,56.000000,167.000000,73.000000,83898.000000,3.593161,16.400000

In [35]:
clf = LogisticRegression()

clf.fit(X_train_tr, Y_train)


Y_pred = clf.predict(X_test_tr)

accuracy_score(Y_pred, Y_test)

C:\Users\lands\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.7222222222222222

## comparison with simpleImputer for accuracy check

In [36]:
si = SimpleImputer()

X_train_trf = si.fit_transform(X_train)
X_test_trf = si.transform(X_test)

In [37]:
clf2 = LogisticRegression()

clf2.fit(X_train_trf, Y_train)


Y_pred2 = clf2.predict(X_test_trf)

accuracy_score(Y_pred2, Y_test)

C:\Users\lands\AppData\Roaming\Python\Python314\site-packages\sklearn\linear_model\_logistic.py:599: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

0.5555555555555556