In [3]:
import numpy as np
import pandas as pd

In [22]:

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer

from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import OrdinalEncoder
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline, make_pipeline

from sklearn.feature_selection import SelectKBest, chi2
from sklearn.metrics import accuracy_score

##Display pipeline

from sklearn import set_config
set_config(display='diagram')

In [5]:
P_records = pd.read_csv('patient_records.csv')
P_records.head(2)

,patient_id,first_name,last_name,gender,age,blood_type,state,smoking_status,insurance_type,primary_condition,height_cm,weight_kg,systolic_bp,diastolic_bp,heart_rate_bpm,last_admission_date
0,PT100000,Sarah,Jackson,Male,0,O+,CA,Former,Private,Type 2 Diabetes,152.3,81.8,71,58,75,2024-07-19
1,PT100001,Jessica,Smith,Female,53,O+,PA,Former,Medicaid,Anxiety Disorder,183.2,45.6,114,89,75,2025-01-16

In [6]:
P_records.isnull().sum()

patient_id              0
first_name              0
last_name               0
gender                  0
age                     0
blood_type             55
state                   0
smoking_status         52
insurance_type          0
primary_condition       5
height_cm              53
weight_kg              48
systolic_bp             0
diastolic_bp            0
heart_rate_bpm          0
last_admission_date     0
dtype: int64

In [7]:
P_records.drop(columns=['patient_id', 'first_name', 'last_name', 'gender', 'insurance_type', 'primary_condition', 'last_admission_date'], inplace=True)

In [8]:
X=P_records[['age', 'blood_type', 'smoking_status', 'height_cm', 'weight_kg', 'systolic_bp', 'diastolic_bp']]
X

,age,blood_type,smoking_status,height_cm,weight_kg,systolic_bp,diastolic_bp
0,0,O+,Former,152.3,81.8,71,58
1,53,O+,Former,183.2,45.6,114,89
2,70,A+,Never,178.1,66.5,104,71
3,52,O+,Former,171.5,NaN,147,77
4,36,O+,Never,169.7,65.0,117,59
...,...,...,...,...,...,...,...
1195,27,NaN,Never,177.1,73.5,136,62
1196,32,O+,Never,175.9,83.8,146,73
1197,52,A+,Current,171.0,66.0,132,94
1198,27,O-,Never,175.2,NaN,157,71
1199,59,A+,Never,181.7,81.9,112,70

In [9]:
Y=P_records['heart_rate_bpm']
Y

0        75
1        75
2        66
3        99
4        72
       ...
1195     87
1196    102
1197     66
1198     94
1199     94
Name: heart_rate_bpm, Length: 1200, dtype: int64

In [10]:
X_train, X_test, Y_train, Y_test=train_test_split(X, Y, test_size=0.4)
X_train, X_test, Y_train, Y_test

(      age blood_type smoking_status  height_cm  weight_kg  systolic_bp  \
 191    35         O+          Never      169.9       73.4          134
 635    90         O-          Never      188.2      101.1          103
 643    50        NaN          Never      158.2      125.0          123
 690    32         O-          Never      165.4       69.0          121
 22      9         O+          Never      172.2        NaN          164
 ...   ...        ...            ...        ...        ...          ...
 608    59         A-          Never      160.8       82.1          119
 724    41         O-         Former      163.4       84.4          129
 1062   82         A-          Never      162.4       77.7          140
 333    20         O-          Never      172.7       93.6          111
 583    78         A+         Former      169.8       77.3          115

       diastolic_bp
 191             94
 635             66
 643             91
 690            107
 22              68
 ...            ...
 608             78
 724             87
 1062            94
 333             88
 583             52

 [720 rows x 7 columns],
       age blood_type smoking_status  height_cm  weight_kg  systolic_bp  \
 916    60        AB-          Never      171.6       92.5          104
 1157   32         A+          Never      164.2       76.6          134
 922    74         A-          Never      155.6      102.9          133
 1189   86         O+          Never      157.6       71.5          121
 148    44         A+        Current      181.5        NaN          121
 ...   ...        ...            ...        ...        ...          ...
 44     56         A+         Former      156.4       63.0          118
 158     2         O+        Current      163.8       77.9          135
 638    26         B+         Former      156.4       55.9          131
 149    12         O-          Never      156.3       79.0          130
 281     9         A+          Never      141.5        NaN          155

       diastolic_bp
 916             89
 1157            75
 922             66
 1189            69
 148             86
 ...            ...
 44              87
 158             76
 638             75
 149             80
 281            111

 [480 rows x 7 columns],
 191      65
 635     104
 643      70
 690      96
 22       56
        ...
 608      82
 724      72
 1062     73
 333      92
 583      81
 Name: heart_rate_bpm, Length: 720, dtype: int64,
 916     81
 1157    63
 922     68
 1189    68
 148     88
         ..
 44      70
 158     75
 638     88
 149     96
 281     77
 Name: heart_rate_bpm, Length: 480, dtype: int64)

In [24]:
### missing values

trs1 = ColumnTransformer([('impute_height_cm', SimpleImputer(), [3]), ('impute_weight_kg', SimpleImputer(), [4]), ('blood_type', SimpleImputer(strategy='most_frequent'), [1]), ('smoking_status', SimpleImputer(strategy='most_frequent'), [2])], remainder='passthrough')

In [17]:
## encoding

trs2 = ColumnTransformer([('ohe_blood_type_smoking_status', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), [1, 2])], remainder='passthrough')

In [18]:
## scaling

trs3=ColumnTransformer([('scale', MinMaxScaler(), slice (0,16))])

In [19]:
## feture selection

trs4 = SelectKBest(score_func=chi2, k=10)

In [20]:
## Logic model

trs5 = DecisionTreeClassifier()

### CReating Pipeline

In [26]:
## Pipeline

pipe = Pipeline([('trs1', trs1), 
                ('trs2', trs2), 
                ('trs3', trs3), 
                ('trs4', trs4), 
                ('trs5', trs5)
                ])

### can also use make_pipeline

In [ ]:
## Alternative

pipe2 = make_pipeline(trs1, trs2, trs3, trs4, trs5)

In [27]:
pipe.fit(X_train, Y_train)

Pipeline(steps=[('trs1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_height_cm',
                                                  SimpleImputer(), [3]),
                                                 ('impute_weight_kg',
                                                  SimpleImputer(), [4]),
                                                 ('blood_type',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [1]),
                                                 ('smoking_status',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [2])])),
                ('trs2',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('ohe_blood_type_smoking_status',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 2])])),
                ('trs3',
                 ColumnTransformer(transformers=[('scale', MinMaxScaler(),
                                                  slice(0, 16, None))])),
                ('trs4',
                 SelectKBest(score_func=<function chi2 at 0x0000015F2B6EA140>)),
                ('trs5', DecisionTreeClassifier())])